/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;


import com.sv.udb.clas.Ejercicio7;
import com.sv.udb.clas.Notas;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author JMagoSV
 */
public class FrmEjerc7 extends javax.swing.JFrame {

    /**
     * Creates new form FrmEjerc7
     */
    public FrmEjerc7() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.poblarData();
    }
    
    private void poblarData()
    {
        this.tblTodo.getTableHeader().setUI(null); //Quitar título de la columna
        //Cambiar color de selección
        this.tblTodo.setSelectionBackground(new Color(255, 255, 204));
        this.tblTodo.setSelectionForeground(Color.BLACK);
        
        
        DefaultTableModel model = (DefaultTableModel)this.tblTodo.getModel();
        while(model.getRowCount()>0){model.removeRow(0);} //Limpiar modelo
        
        
        //Obtenes y cargar la data CSV
        Ejercicio7 obje = new Ejercicio7();
        for(Notas temp : obje.getData())
        {
            String text = String.format("<html><div style='display:table'><div><div><strong> %s</strong> "
                + "</div></div><div style='color:gray'>%s</div></div></html>", 
                    temp.getTitu(), temp.getDesc());
            Object[] arre = new Object[2];
            arre[0] = text;
            arre[1] = temp.getFech();
            model.addRow(arre);
//            model.addRow(new Object[]{text, temp.getFech()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTodo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarDescripcion = new javax.swing.JTextArea();
        txtfecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblTodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Datos", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTodo.setRowHeight(30);
        tblTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTodoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTodo);
        if (tblTodo.getColumnModel().getColumnCount() > 0) {
            tblTodo.getColumnModel().getColumn(0).setResizable(false);
            tblTodo.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        txtTitulo.setEditable(false);
        txtTitulo.setBackground(new java.awt.Color(255, 255, 204));
        txtTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtTitulo.setText("Titulo");
        txtTitulo.setBorder(null);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane2.setBorder(null);

        tarDescripcion.setBackground(new java.awt.Color(255, 255, 204));
        tarDescripcion.setColumns(20);
        tarDescripcion.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tarDescripcion.setLineWrap(true);
        tarDescripcion.setRows(5);
        tarDescripcion.setBorder(null);
        jScrollPane2.setViewportView(tarDescripcion);

        txtfecha.setEditable(false);
        txtfecha.setBackground(new java.awt.Color(255, 255, 204));
        txtfecha.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtfecha.setText("fecha");
        txtfecha.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTodoMouseClicked

        if (tblTodo.getSelectedRow() > -1){
            Ejercicio7 ejer = new Ejercicio7();
            Notas fila =  ejer.getData().get(tblTodo.getSelectedRow());
            txtTitulo.setText(fila.getTitu());
            tarDescripcion.setText(fila.getDesc());
        }
    }//GEN-LAST:event_tblTodoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEjerc7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tarDescripcion;
    private javax.swing.JTable tblTodo;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables
}
